### ISSUE TITLE
Can you support Limbo Page? There are many interesting things.

### ISSUE THREAD

**Issue by piano777wzy** [CG8516/PvZA11y#25] opened 2023-12-27 12:06 UTC
Hey, hello, I found some interesting content, today I used a tool, I found a button called full unlock inside, I clicked, so that every mode in the game has a new function called Limbo Page, but we can't find these hides, I have to use an ocr to operate.
Well, even if I go in through ocr, but I use up.down to choose, I will make a crazy mistake and have no way to choose the content.
Can you support these hidden contents?
Thank you

**Comment by CG8516** [comment] 2023-12-27 12:25
Hey. Sorry, but these aren't a high priority right now, as they aren't a normal feature of the game, and are only available by hacking the game. Also, this is a duplicate of issue #24

**Closed by CG8516** 2023-12-27 12:25 UTC
